config/routes.rb
Rails.application.routes.draw do
   root 'welcome#index'

   get 'signup', to: 'users#new'
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'
   get 'search_friends', to: 'users#search'
   post 'add_friend', to: 'users#add_friend'
   get 'add_friend', to: 'users#add_friend'

   get 'my_friends', to: 'users#my_friends'
   resources :categories, except: [:destroy]
   resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users, except: [:new]
    resources :users, only: [:show]
    resources :tweets do
    resources :comments
  end


end

app/views/friends/_lookup.html.erb
<br>
  <% if @users %>
    <% if @users.size > 0 %>
      <div id="friend-lookup-results" class="well results-block col-md-10">
        <table class="search-results-table col-md-12">
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><strong>Name:</strong> <%= user.username %></td>
              <td><strong>Email:</strong> <%= user.email %></td>
              <td><strong>Profile:</strong> <%= link_to "View Profile", user_path(user),
                                                        class: "btn btn-xs btn-success" %>
                <% if current_user.not_friends_with?(user.id) %>
                  <%= link_to "Add as my friend", add_friend_path(user: current_user, friend: user),
                                                    class: "btn btn-xs btn-success", method: :post %>
                <% else %>
                  <span class="label label-primary">
                    You are friends
                  </span>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <p class="lead col-md-12">
        No people match this search criteria
      </p>
    <% end %>
  <% end %>
  <div id="friend-lookup-errors"></div>
</div>