config/routes.rb
Rails.application.routes.draw do
   root 'welcome#index'

   get 'signup', to: 'users#new'
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'
   get 'search_friends', to: 'users#search'
   post 'add_friend', to: 'users#add_friend'
   get 'add_friend', to: 'users#add_friend'

   get 'my_friends', to: 'users#my_friends'
   resources :categories, except: [:destroy]
   resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users, except: [:new]
    resources :users, only: [:show]
    resources :tweets do
    resources :comments
  end


end

app/models/user.rb
class User < ActiveRecord::Base

    has_many :tweets, dependent: :destroy
    has_many :comments
    has_many :friendships
    has_many :friends, through: :friendships
  before_save { self.email = email.downcase }

  validates :username, presence: true,uniqueness: { case_sensitive: false },length: { minimum: 3, maximum: 25 }

 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, presence: true, length: { maximum: 105 },uniqueness: { case_sensitive: false },format: { with: VALID_EMAIL_REGEX }

  has_secure_password

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def self.search(param)
    return User.none if param.blank?

    param.strip!
    param.downcase!
    (username_matches(param) + email_matches(param)).uniq
  end

  def self.username_matches(param)
    matches('username', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(username, param)
    where("lower(#{username}) like ?", "%#{param}%")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]



  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

   def my_friends
     @friendships = current_user.friends

   end

   def search
    @users = User.search(params[:search_params])

    if @users
      @users = current_user.except_current_user(@users)
      render partial: "friends/lookup"
    else
      render status: :not_found, nothing: true
    end
   end

 def add_friend
  @friend = User.find(params[:friend])
  current_user.friendships.build(friend_id: @friend.id)

  if current_user.save
    redirect_to my_friends_path, notice: "Friend was successfully added"
  else
    redirect_to my_friends_path, flash[:error] = "There was an error adding user as friend"
  end
 end

def new
    @user = User.new
end

def show
  @user = User.find(params[:id])
  @user_tweets = @user.tweets
end

def create
      @user = User.new(user_params)
       if @user.save
         session[:user_id] = @user.id
          flash[:success] = "Welcome to tweet book #{@user.username}"
          redirect_to user_path(@user)
      else
        render 'new'
      end

end

    def edit
      @user = User.find(params[:id])
    end

def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:success] = "Your account was updated successfully"
        redirect_to tweets_path
      else
        render 'edit'
      end
end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all articles created by user have been deleted"
        redirect_to users_path
    end

private

    def user_params
    params.require(:user).permit(:username, :email, :password)
   end

   def require_same_user
        if current_user != @user and !current_user.admin?
        flash[:danger] = "You can only edit your own account"
        redirect_to root_path
        end
    end

    def require_admin
      if logged_in? and !current_user.admin?
          flash[:danger] = "Only admin users can perform that action"
          redirect_to root_path
      end
   end

end

app/views/users/_form.html.erb
<br><br>  <%= render 'shared/errors', obj: @user %>

<div class='row'>

<div class='col-xs-12'>

<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :username %>

</div>

<div class="col-sm-8">

<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :email %>

</div>

<div class="col-sm-8">

<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :password %>

</div>

<div class="col-sm-8">

<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>

</div>

</div>

<div class="form-group">

<div class="col-sm-offset-2 col-sm-10">

<%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>

</div>

</div>

<% end %>



</div>

</div>
<br><br>
<%= render 'layouts/footer' %> 

app/views/users/edit.html.erb
<br><br><br><h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All TweetBook Users</h1>

<div align="center">


<%= will_paginate %>
<% @users.each do |user| %>

<ul class="listing">

<div class="row">

<div class="well col-md-4 col-md-offset-4">



<ul class="tweet-title">

<%= link_to user.username, user_path(user) %>

</ul>

<ul><small><%= pluralize(user.tweets.count, "tweet") if user.tweets %></small></ul>

<% if logged_in? and current_user.admin? %>

<ul> <%= button_to "Delete this user", user_path(user), :method => :delete, :confirm => "You sure?"%>  </ul>


<% end %>

<% if current_user.not_friends_with?(user.id) %>
  <%= link_to "Add as my friend", add_friend_path(user: current_user, friend: user),
                                    class: "btn btn-xs btn-success", method: :post %>
<% else %>
  <div >


    <%= link_to "View Profile", user_path(user), class:"btn btn-primary btn-xs" %>
    <br>
    <%= button_to "Remove Friend", friendship_path(user), :method => :delete, :confirm => "You sure?"%> </td>
    </div>
<% end %>

</div>

</div>

</ul>


<% end %>
<%= will_paginate %>
</div>

<br><br>
<%= render 'layouts/footer' %> 

app/views/users/my_friends.html.erb
<br><br>


<%= render 'friends/lookup' %>
<% if @friendships.size > 0 %>
   <table class="table table-stripped">
     <thead>
       <tr>
         <th colspan="3" class="page-header">
          <h2>My Friends</h2>
         </th>
       </tr>
<tr>
           <th> Name</th>
            <th> Email</th>
            <th> Actions</th>
       </tr>
     </thead>
     <body>
       <% @friendships.each do |friend| %>
       <tr>
         <td> <%= friend.username %></td>
         <td> <%= friend.email %></td>
         <td> <%= link_to "View Profile", user_path(friend), class:"btn btn-primary btn-xs" %>
         <%= button_to "Remove Friend", friendship_path(friend), :method => :delete, :confirm => "You sure?"%> </td>
       </tr>
       <% end %>
     </body>
   </table>
<% else %>
      <div class="row col-lg-12">
        <p class="lead">You don't have any friends yet. Please add some!</p>
      </div>
<% end %>

<br><br><br>

<%= render 'layouts/footer' %> 

app/views/users/new.html.erb
<br><br><h1 align="center">Sign up for Tweet Book</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<br><br><br>

<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="row">

<div class="col-md-4 col-md-offset-4 center">

</div>

</div>

<h4 align="center"><%= @user.username %>'s tweets</h4>
<%= render 'tweets/tweet', obj: @user_tweets %>


<br><br>
<br><br><br><br>
<%= render 'layouts/footer' %>