config/routes.rb
Rails.application.routes.draw do
   root 'welcome#index'

   get 'signup', to: 'users#new'
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'
   get 'search_friends', to: 'users#search'
   post 'add_friend', to: 'users#add_friend'
   get 'add_friend', to: 'users#add_friend'

   get 'my_friends', to: 'users#my_friends'
   resources :categories, except: [:destroy]
   resources :friendships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users, except: [:new]
    resources :users, only: [:show]
    resources :tweets do
    resources :comments
  end


end

app/views/layouts/_footer.html.erb
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <!-- // -->

  <div class="container">

    <footer> &copy; Copyright 2017, Likki & Soni <br/> All rights reserved. </footer>

      <hr />
          <div class="text-center center-block">
              <br />
                <a href="https://www.facebook.com/likhith.acharya"><i class="fa fa-facebook-square fa-3x social"></i></a>
                  <a href="https://www.facebook.com/arjun.soni.001"><i class="fa fa-facebook-square fa-3x social"></i></a>
                <a href="https://twitter.com/likhithacharya"><i class="fa fa-twitter-square fa-3x social"></i></a>
                <a href="https://plus.google.com/106892259531428463432"><i class="fa fa-google-plus-square fa-3x social"></i></a>
                <a href="mailto:likhithacharya277@gmail.com"><i class="fa fa-envelope-square fa-3x social"></i></a>

  </div>

app/views/layouts/_messages.html.erb
<div class="row">

<div class="col-xs-10 col-xs-offset-1">

<% flash.each do |name, msg| %>

<div class='alert alert-<%="#{name}" %>'>

<a href="#" class="close" data-dismiss="alert">×</a>

<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>

</div>

<% end %>

</div>

</div>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse " role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
                <%= link_to "TweetBook", root_path, class: "navbar-brand",id:"logo" %>

        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

                     <% if logged_in?  %>
                            <li><%= link_to "Home" , root_path, class: "nav-icon" %></li>
                           <li><%= link_to "Users" , users_path,class: "nav-icon"  %></li>

                            <li> <%= link_to "Tweets",  tweets_path, class: "nav-icon" %> </li>
                            <li><%= link_to "New tweet" , new_tweet_path, class: "nav-icon" %></li>
                            <li> <%= link_to "List of my tweets",  user_path(current_user), class: "nav-icon" %> </li>
                            <li><%= link_to "My Friends" , my_friends_path, class: "nav-icon" %></li>
                            <li><%#= link_to "Edit your profile", edit_user_path(current_user), class: "nav-icon"  %> </li> <br>
                            <li><%= button_to "Logout", logout_path, :method => :delete, :confirm => "You sure?"%></li>

                        <% else %>
                            <li><%= link_to "Home" , root_path, class: "nav-icon" %></li>
                            <li><%= link_to "Log in" , login_path, class: "nav-icon" %></li>
                            <li><%= link_to "sign up" , signup_path, class: "nav-icon" %></li>
                     <% end %>
                 </ul>

                      </ul>
                      </li>

                      <li class="dropdown">

        <ul class="dropdown-menu">

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->

        <% Category.all.each do |category| %>
        <% if logged_in?  %>
            <li ><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
        <% end %>
        <% if logged_in? and current_user.admin? %>
     <li><%= link_to "Create new category" , new_category_path %></li>
       <% end %>
  </ul>
</li>
</nav>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetBook</title>
    <%= csrf_meta_tags %>


 <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


    <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/navigation' %>


    <%= yield %>
 
  </body>
</html>